version: "3.9"
services:

  vernemq:
    image: vernemq
    container_name: vernemq
    labels:
      - "com.iotportaldevicemanagement.product=iotportaldevicemanagement"
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "10"
    restart: always
#    read_only: true
    environment:
      DOCKER_VERNEMQ_ACCEPT_EULA: '${DOCKER_VERNEMQ_ACCEPT_EULA}'
      DOCKER_VERNEMQ_ALLOW_ANONYMOUS: '${DOCKER_VERNEMQ_ALLOW_ANONYMOUS}'
      DOCKER_VERNEMQ_LOG__CONSOLE: '${DOCKER_VERNEMQ_LOG__CONSOLE}'
      DOCKER_VERNEMQ_SYSTREE_ENABLED: '${DOCKER_VERNEMQ_SYSTREE_ENABLED}'
#      DOCKER_VERNEMQ_LISTENER__SSL__CAFILE: '${DOCKER_VERNEMQ_LISTENER__SSL__CAFILE}'
#      DOCKER_VERNEMQ_LISTENER__SSL__CERTFILE: '${DOCKER_VERNEMQ_LISTENER__SSL__CERTFILE}'
#      DOCKER_VERNEMQ_LISTENER__SSL__KEYFILE: '${DOCKER_VERNEMQ_LISTENER__SSL__KEYFILE}'
      DOCKER_VERNEMQ_PLUGINS__VMQ_ACL: '${DOCKER_VERNEMQ_PLUGINS__VMQ_ACL}'
      DOCKER_VERNEMQ_PLUGINS__VMQ_WEBHOOKS: '${DOCKER_VERNEMQ_PLUGINS__VMQ_WEBHOOKS}'
      DOCKER_VERNEMQ_VMQ_WEBHOOKS__AUTH_ON_REGISTER__HOOK: '${DOCKER_VERNEMQ_VMQ_WEBHOOKS__AUTH_ON_REGISTER__HOOK}'
      DOCKER_VERNEMQ_VMQ_WEBHOOKS__AUTH_ON_REGISTER__ENDPOINT: '${DOCKER_VERNEMQ_VMQ_WEBHOOKS__AUTH_ON_REGISTER__ENDPOINT}'
      DOCKER_VERNEMQ_VMQ_WEBHOOKS__AUTH_ON_SUBSCRIBE__HOOK: '${DOCKER_VERNEMQ_VMQ_WEBHOOKS__AUTH_ON_SUBSCRIBE__HOOK}'
      DOCKER_VERNEMQ_VMQ_WEBHOOKS__AUTH_ON_SUBSCRIBE__ENDPOINT: '${DOCKER_VERNEMQ_VMQ_WEBHOOKS__AUTH_ON_SUBSCRIBE__ENDPOINT}'
      DOCKER_VERNEMQ_VMQ_WEBHOOKS__AUTH_ON_PUBLISH__HOOK: '${DOCKER_VERNEMQ_VMQ_WEBHOOKS__AUTH_ON_PUBLISH__HOOK}'
      DOCKER_VERNEMQ_VMQ_WEBHOOKS__AUTH_ON_PUBLISH__ENDPOINT: '${DOCKER_VERNEMQ_VMQ_WEBHOOKS__AUTH_ON_PUBLISH__ENDPOINT}'
      DOCKER_VERNEMQ_VMQ_WEBHOOKS__ON_CLIENT_OFFLINE__HOOK: '${DOCKER_VERNEMQ_VMQ_WEBHOOKS__ON_CLIENT_OFFLINE__HOOK}'
      DOCKER_VERNEMQ_VMQ_WEBHOOKS__ON_CLIENT_OFFLINE__ENDPOINT: '${DOCKER_VERNEMQ_VMQ_WEBHOOKS__ON_CLIENT_OFFLINE__ENDPOINT}'
      DOCKER_VERNEMQ_VMQ_WEBHOOKS__ON_CLIENT_GONE__HOOK: '${DOCKER_VERNEMQ_VMQ_WEBHOOKS__ON_CLIENT_GONE__HOOK}'
      DOCKER_VERNEMQ_VMQ_WEBHOOKS__ON_CLIENT_GONE__ENDPOINT: '${DOCKER_VERNEMQ_VMQ_WEBHOOKS__ON_CLIENT_GONE__ENDPOINT}'
#      DOCKER_VERNEMQ_VMQ_WEBHOOKS__CAFILE: '${DOCKER_VERNEMQ_VMQ_WEBHOOKS__CAFILE}'
#      DOCKER_VERNEMQ_VMQ_WEBHOOKS__USE_CRLS: '${DOCKER_VERNEMQ_VMQ_WEBHOOKS__USE_CRLS}'
#    volumes:
#      - ../iotportaldata/vernemq/etc:/vernemq/etc
#      - ../iotportaldata/vernemq/data:/vernemq/data
#      - ../iotportaldata/ssl:/vernemq/ssl
#    tmpfs:
#      - /tmp:uid=${LOCAL_UID},gid=${LOCAL_GID}
    ports:
      - "${DOCKER_VERNEMQ_TCP_PORT:-1883}:1883"
#      - "${DOCKER_VERNEMQ_SSL_PORT:-8883}:8883"
    networks:
      - iotportaldevicemanagement

networks:
  iotportaldevicemanagement:
    driver: bridge